### ISSUE TITLE
bootstrap4

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii-debug-frontend#6]
обновление будет под yiisoft/yii2-bootstrap4 ?

**Comment by lav45** [comment]
@samdark Немного наоборот ))
Я имел в виду стили сайта может немного коверкать yii-debug панель.

В данном случае @cebe предполагает случай одновременного использования **bootstrap 4** для сайта и **bootstrap 3** для yii-debug панели.

**Comment by samdark** [comment]
Toolbar isn't using bootstrap at all: https://github.com/yiisoft/yii-debug/blob/master/src/assets/toolbar.css. Bootstrap is used for debugger itself.

**Comment by samdark** [comment]
Closing since the issue isn't up to date with current code/approach.
